# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceid', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('pendingrequest', models.BooleanField()),
                ('requestgranted', models.BooleanField()),
                ('imagebytes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('deviceid', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('wasgranted', models.BooleanField()),
                ('imagebytes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('pwhash', models.BinaryField()),
                ('phonenum', models.TextField()),
                ('deviceid', models.TextField()),
            ],
        ),
    ]
