# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='username',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagemonitor',
            name='didhash',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='packagemonitor',
            name='pwhash',
            field=models.BinaryField(),
        ),
    ]
